apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: java-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-microservice
    spec:
      containers:
      - name: durga-java-microservice-container
        image: 088585194665.dkr.ecr.ap-south-1.amazonaws.com/durga-cicd:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: "durga-service-java-microservice"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: Nodeport
  selector:
    app.kubernetes.io/name: java-microservice
